[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/pterror/resin"

[workspace.dependencies]
# Math (bevy-compatible)
glam = "0.29"

# Error handling
thiserror = "2"
