[package]
name = "rhizome-resin-geometry"
version = "0.1.0"
edition = "2024"
description = "Geometry attribute traits for resin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
glam.workspace = true
