[package]
name = "rhizome-resin-audio-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Audio graph codegen for resin-audio"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }
